
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: redis
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: redis:3.2.7
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
