apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
  namespace: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      restartPolicy: Always
      containers:
      - command:
        - /entrypoint.sh
        args:  ["scheduler"]
        image: puckel/docker-airflow:1.8.2
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: git-volume
        name: airflow
        envFrom:
        - configMapRef:
            name: config-airflow
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/emirot/dags.git"
          revision: "7fd5ae5df7a7925d50b73e7c66ce013ef6165a70"