apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: airflow
spec:
  type: LoadBalancer
  selector:
    app: airflow
    tier: web
  ports:
    - name: web
      protocol: TCP
      port: 8080